Feature/413912 integrate get api
DEFRA/epr-calculator-frontend pull request #21
Opened 2024-08-08 12:45 UTC by Skumarhpa

2024-08-08 13:00 UTC, johnbenjamin-defra requested changes
@Skumarhpa - couple of minor observations.

2024-08-08 13:00 UTC, johnbenjamin-defra commented on src/EPR.Calculator.Frontend/Models/DefaultSchemeParameters.cs
> +    public class DefaultSchemeParameters
@Skumarhpa - Exclude this file from code coverage please...

2024-08-08 13:34 UTC, johnbenjamin-defra approved these changes

2024-08-08 13:41 UTC, udaydefra approved these changes
LGTM

2024-08-09 14:44 UTC, johnbenjamin-defra approved these changes

2024-08-12 10:21 UTC, johnbenjamin-defra approved these changes

2024-08-13 13:39 UTC, merged