Feature/426687 lapcap problem with upload
DEFRA/epr-calculator-frontend pull request #47
Opened 2024-09-16 09:23 UTC by Skumarhpa

2024-09-16 12:21 UTC, johnbenjamin-defra approved these changes

2024-09-16 13:16 UTC, udaydefra commented on src/EPR.Calculator.Frontend/Helpers/CsvFileHelper.cs
> +            if (fileUpload.Length > StaticHelpers.MaxFileSize && !isLapCapData)
Not sure why you need this `isLapCapData`

2024-09-16 13:16 UTC, udaydefra commented on src/EPR.Calculator.Frontend/Helpers/CsvFileHelper.cs
> +        public static ErrorViewModel ValidateCSV(IFormFile fileUpload, bool isLapCapData = false)
Not sure why you need this `isLapCapData`

2024-09-16 14:10 UTC, udaydefra submitted a review, later dismissed
LGTM

2024-09-16 14:10 UTC, johnbenjamin-defra submitted a review, later dismissed

2024-09-16 15:58 UTC, rekhadhankhar2018 approved these changes

2024-09-19 09:15 UTC, johnbenjamin-defra requested changes

2024-09-19 09:15 UTC, johnbenjamin-defra commented on src/EPR.Calculator.Frontend/Views/Shared/_ValidationErrorsListPartial.cshtml
> +﻿@model List<CreateLapcapDataErrorDto>;
I think this partial view is shared with default parameters. I think we do not need a partial view in this case as the model is different. Could you please check?

2024-09-19 10:04 UTC, rekhadhankhar2018 submitted a review, later dismissed

2024-09-19 10:37 UTC, johnbenjamin-defra approved these changes

2024-09-19 11:15 UTC, rekhadhankhar2018 approved these changes

2024-10-01 09:32 UTC, johnbenjamin-defra approved these changes

2024-10-01 09:32 UTC, rekhadhankhar2018 approved these changes

2024-10-01 09:32 UTC, Mazar-Shaik approved these changes

2024-10-01 09:53 UTC, closed without merging