Feature/482149 results file download
DEFRA/epr-calculator-frontend pull request #97
Opened 2024-12-18 10:06 UTC by davidjayakumarEviden

482149 Results file download - Integrate GET results file Endpoint

2024-12-18 13:20 UTC, udaydefra commented on src/EPR.Calculator.Frontend/Controllers/CalculationRunDetailsController.cs
> +                this.ViewBag.ErrorPage = $"DownloadFileError?runId={runId}&calcName={calcName}&createdDate={statusUpdateViewModel.Data.CreatedDate}" +
Please use HttpUtility.UrlEncode Method

2024-12-18 13:21 UTC, udaydefra commented on src/EPR.Calculator.Frontend/Views/CalculationRunDetails/Index.cshtml
> +                    <a href="javascript:void(0)" onclick="downloadFile('@DownloadAPI', '@ErrorPage', event);" class="govuk-link" target="_self">Download</a><br />
Please create Constants in C# Template and pass them instead of Javascript strings for '@DownloadAPI', '@ErrorPage',

2024-12-18 13:24 UTC, udaydefra commented on src/EPR.Calculator.Frontend/wwwroot/js/Download.js
> +    $.ajax({
You might have to introduce a Timeout parameter in the configuration and pass it as a parameter
This is needed as Downloading a file might take a while [Large Files]
I can help you with that in a call. Thanks

2024-12-18 13:25 UTC, johnbenjamin-defra requested changes

2024-12-18 13:25 UTC, johnbenjamin-defra commented on src/EPR.Calculator.Frontend/Views/DownloadFileError/Index.cshtml
> +        <div class="govuk-grid-column-one-quarter govuk-body-s govuk-!-margin-top-4">
I think you can use the partial view here _src/EPR.Calculator.Frontend/Views/Shared/_BackLinkPartial.cshtml_

2024-12-18 13:26 UTC, udaydefra commented on src/EPR.Calculator.Frontend/wwwroot/js/Download.js
> +            var contentDisposition = xhr.getResponseHeader('Content-Disposition');
Even in success you might need to have a try/catch

`
   success: function (data, status, xhr) {
try {
  // Do the processing 
}
catch(err) {
  window.location.href = errorAction;
}
} // end of success
`

2024-12-18 13:28 UTC, tim-powell-eviden reviewed
Some SonarQube issues:
https://vss-sonarqube.azure.defra.cloud/project/issues?resolved=false&inNewCodePeriod=true&pullRequest=97&id=epr-calculator-frontend

2024-12-18 14:33 UTC, davidjayakumarEviden commented on src/EPR.Calculator.Frontend/Controllers/CalculationRunDetailsController.cs
> +                this.ViewBag.ErrorPage = $"DownloadFileError?runId={runId}&calcName={calcName}&createdDate={statusUpdateViewModel.Data.CreatedDate}" +
HttpUtility.UrlPathEncode() works

2024-12-18 15:32 UTC, johnbenjamin-defra approved these changes

2024-12-19 17:03 UTC, udaydefra commented on src/EPR.Calculator.Frontend/appsettings.Development.json
> +        "DownloadResultTimeout":  30000
Sorry bieng pedantic, can you change the parameterName to DownloadResultTimeoutInSeconds

2024-12-20 11:12 UTC, udaydefra commented on src/EPR.Calculator.Frontend/Controllers/CalculationRunDetailsController.cs
> +            statusUpdateViewModel.DownloadTimeout = Convert.ToInt32(this.configuration
Always use int.TryParse

2024-12-20 11:14 UTC, tim-powell-eviden approved these changes

2024-12-20 11:35 UTC, udaydefra approved these changes

2024-12-20 11:48 UTC, johnbenjamin-defra approved these changes

2024-12-23 10:10 UTC, merged